### ISSUE TITLE
Can a new hackage revision be made that updates the url in the synopsis

### ISSUE THREAD

**Issue by pranaysashank** [codedownio/hs-webdriver#1]
I looked at the webdriver package on hackage multiple times and kept assuming it's not maintained, because I'd go to the first link displayed in the `description` section displayed from `webdriver.cabal` file. I think it makes sense to make a revision to update the url in there. It's already updated on master https://github.com/codedownio/hs-webdriver/commit/e63f96fc9ebc82b70a7ea9bf3ba0c1dea5c80048

**Comment by thomasjm** [comment]
Yes, will do this soon! We're currently in the process of moving the original repo to a GitHub organization, so once that's done we'll update everything to point there.

**Comment by thomasjm** [comment]
Done!
